# Types byte definition
TNULL = b'\x00'
TINT = b'\x01'
TFLOAT = b'\x02'
TTIME = b'\x03'
TDURATION = b'\x04'
TERROR = b'\x05'
TSTRING = b'\x06'
TARRAY = b'\x07'
TARRAYSERIAL = b'\x08'
TTIMESERIE = b'\x09'
TSENTINEL = b'\x0A'
TBOOL = b'\x0B'
TDEC64 = b'\x0C'
TPAIR = b'\x0D'
THEARTBEAT = b'\x0E'
TTENSOR = b'\x0F' #experimental type, May change in the future
